//! Every WAI-ARIA 1.2 state and property, extracted from `index.html` of
//! w3c/aria's `2023-06_REC` branch (commit `66caad8`): its "Used in Roles"
//! applicability, value type, and the values table with its default.

use super::attributes::{Attribute, Scope, ValueType};

pub(super) const ATTRIBUTES: &[Attribute] = &[
    Attribute {
        name: "aria-activedescendant",
        is_state: false,
        value_type: ValueType::IdRef,
        values: &[],
        default: None,
        scope: Scope::RoleSpecific,
        is_deprecated: false,
    },
    Attribute {
        name: "aria-atomic",
        is_state: false,
        value_type: ValueType::TrueFalse,
        values: &["false", "true"],
        default: Some("false"),
        scope: Scope::Global,
        is_deprecated: false,
    },
    Attribute {
        name: "aria-autocomplete",
        is_state: false,
        value_type: ValueType::Token,
        values: &["inline", "list", "both", "none"],
        default: Some("none"),
        scope: Scope::RoleSpecific,
        is_deprecated: false,
    },
    Attribute {
        name: "aria-busy",
        is_state: true,
        value_type: ValueType::TrueFalse,
        values: &["false", "true"],
        default: Some("false"),
        scope: Scope::Global,
        is_deprecated: false,
    },
    Attribute {
        name: "aria-checked",
        is_state: true,
        value_type: ValueType::Tristate,
        values: &["false", "mixed", "true", "undefined"],
        default: Some("undefined"),
        scope: Scope::RoleSpecific,
        is_deprecated: false,
    },
    Attribute {
        name: "aria-colcount",
        is_state: false,
        value_type: ValueType::Integer,
        values: &[],
        default: None,
        scope: Scope::RoleSpecific,
        is_deprecated: false,
    },
    Attribute {
        name: "aria-colindex",
        is_state: false,
        value_type: ValueType::Integer,
        values: &[],
        default: None,
        scope: Scope::RoleSpecific,
        is_deprecated: false,
    },
    Attribute {
        name: "aria-colspan",
        is_state: false,
        value_type: ValueType::Integer,
        values: &[],
        default: None,
        scope: Scope::RoleSpecific,
        is_deprecated: false,
    },
    Attribute {
        name: "aria-controls",
        is_state: false,
        value_type: ValueType::IdRefList,
        values: &[],
        default: None,
        scope: Scope::Global,
        is_deprecated: false,
    },
    Attribute {
        name: "aria-current",
        is_state: true,
        value_type: ValueType::Token,
        values: &["page", "step", "location", "date", "time", "true", "false"],
        default: Some("false"),
        scope: Scope::Global,
        is_deprecated: false,
    },
    Attribute {
        name: "aria-describedby",
        is_state: false,
        value_type: ValueType::IdRefList,
        values: &[],
        default: None,
        scope: Scope::Global,
        is_deprecated: false,
    },
    Attribute {
        name: "aria-details",
        is_state: false,
        value_type: ValueType::IdRef,
        values: &[],
        default: None,
        scope: Scope::Global,
        is_deprecated: false,
    },
    Attribute {
        name: "aria-disabled",
        is_state: true,
        value_type: ValueType::TrueFalse,
        values: &["false", "true"],
        default: Some("false"),
        scope: Scope::GlobalDeprecated,
        is_deprecated: false,
    },
    Attribute {
        name: "aria-dropeffect",
        is_state: false,
        value_type: ValueType::TokenList,
        values: &["copy", "execute", "link", "move", "none", "popup"],
        default: Some("none"),
        scope: Scope::Global,
        is_deprecated: true,
    },
    Attribute {
        name: "aria-errormessage",
        is_state: false,
        value_type: ValueType::IdRef,
        values: &[],
        default: None,
        scope: Scope::GlobalDeprecated,
        is_deprecated: false,
    },
    Attribute {
        name: "aria-expanded",
        is_state: true,
        value_type: ValueType::TrueFalseUndefined,
        values: &["false", "true", "undefined"],
        default: Some("undefined"),
        scope: Scope::RoleSpecific,
        is_deprecated: false,
    },
    Attribute {
        name: "aria-flowto",
        is_state: false,
        value_type: ValueType::IdRefList,
        values: &[],
        default: None,
        scope: Scope::Global,
        is_deprecated: false,
    },
    Attribute {
        name: "aria-grabbed",
        is_state: true,
        value_type: ValueType::TrueFalseUndefined,
        values: &["false", "true", "undefined"],
        default: Some("undefined"),
        scope: Scope::Global,
        is_deprecated: true,
    },
    Attribute {
        name: "aria-haspopup",
        is_state: false,
        value_type: ValueType::Token,
        values: &["false", "true", "menu", "listbox", "tree", "grid", "dialog"],
        default: Some("false"),
        scope: Scope::GlobalDeprecated,
        is_deprecated: false,
    },
    Attribute {
        name: "aria-hidden",
        is_state: true,
        value_type: ValueType::TrueFalseUndefined,
        values: &["false", "true", "undefined"],
        default: Some("undefined"),
        scope: Scope::Global,
        is_deprecated: false,
    },
    Attribute {
        name: "aria-invalid",
        is_state: true,
        value_type: ValueType::Token,
        values: &["grammar", "false", "spelling", "true"],
        default: Some("false"),
        scope: Scope::GlobalDeprecated,
        is_deprecated: false,
    },
    Attribute {
        name: "aria-keyshortcuts",
        is_state: false,
        value_type: ValueType::String,
        values: &[],
        default: None,
        scope: Scope::Global,
        is_deprecated: false,
    },
    Attribute {
        name: "aria-label",
        is_state: false,
        value_type: ValueType::String,
        values: &[],
        default: None,
        scope: Scope::Global,
        is_deprecated: false,
    },
    Attribute {
        name: "aria-labelledby",
        is_state: false,
        value_type: ValueType::IdRefList,
        values: &[],
        default: None,
        scope: Scope::Global,
        is_deprecated: false,
    },
    Attribute {
        name: "aria-level",
        is_state: false,
        value_type: ValueType::Integer,
        values: &[],
        default: None,
        scope: Scope::RoleSpecific,
        is_deprecated: false,
    },
    Attribute {
        name: "aria-live",
        is_state: false,
        value_type: ValueType::Token,
        values: &["assertive", "off", "polite"],
        default: Some("off"),
        scope: Scope::Global,
        is_deprecated: false,
    },
    Attribute {
        name: "aria-modal",
        is_state: false,
        value_type: ValueType::TrueFalse,
        values: &["false", "true"],
        default: Some("false"),
        scope: Scope::RoleSpecific,
        is_deprecated: false,
    },
    Attribute {
        name: "aria-multiline",
        is_state: false,
        value_type: ValueType::TrueFalse,
        values: &["false", "true"],
        default: Some("false"),
        scope: Scope::RoleSpecific,
        is_deprecated: false,
    },
    Attribute {
        name: "aria-multiselectable",
        is_state: false,
        value_type: ValueType::TrueFalse,
        values: &["false", "true"],
        default: Some("false"),
        scope: Scope::RoleSpecific,
        is_deprecated: false,
    },
    Attribute {
        name: "aria-orientation",
        is_state: false,
        value_type: ValueType::Token,
        values: &["horizontal", "undefined", "vertical"],
        default: Some("undefined"),
        scope: Scope::RoleSpecific,
        is_deprecated: false,
    },
    Attribute {
        name: "aria-owns",
        is_state: false,
        value_type: ValueType::IdRefList,
        values: &[],
        default: None,
        scope: Scope::Global,
        is_deprecated: false,
    },
    Attribute {
        name: "aria-placeholder",
        is_state: false,
        value_type: ValueType::String,
        values: &[],
        default: None,
        scope: Scope::RoleSpecific,
        is_deprecated: false,
    },
    Attribute {
        name: "aria-posinset",
        is_state: false,
        value_type: ValueType::Integer,
        values: &[],
        default: None,
        scope: Scope::RoleSpecific,
        is_deprecated: false,
    },
    Attribute {
        name: "aria-pressed",
        is_state: true,
        value_type: ValueType::Tristate,
        values: &["false", "mixed", "true", "undefined"],
        default: Some("undefined"),
        scope: Scope::RoleSpecific,
        is_deprecated: false,
    },
    Attribute {
        name: "aria-readonly",
        is_state: false,
        value_type: ValueType::TrueFalse,
        values: &["false", "true"],
        default: Some("false"),
        scope: Scope::RoleSpecific,
        is_deprecated: false,
    },
    Attribute {
        name: "aria-relevant",
        is_state: false,
        value_type: ValueType::TokenList,
        values: &["additions", "all", "removals", "text"],
        default: Some("additions text"),
        scope: Scope::Global,
        is_deprecated: false,
    },
    Attribute {
        name: "aria-required",
        is_state: false,
        value_type: ValueType::TrueFalse,
        values: &["false", "true"],
        default: Some("false"),
        scope: Scope::RoleSpecific,
        is_deprecated: false,
    },
    Attribute {
        name: "aria-roledescription",
        is_state: false,
        value_type: ValueType::String,
        values: &[],
        default: None,
        scope: Scope::Global,
        is_deprecated: false,
    },
    Attribute {
        name: "aria-rowcount",
        is_state: false,
        value_type: ValueType::Integer,
        values: &[],
        default: None,
        scope: Scope::RoleSpecific,
        is_deprecated: false,
    },
    Attribute {
        name: "aria-rowindex",
        is_state: false,
        value_type: ValueType::Integer,
        values: &[],
        default: None,
        scope: Scope::RoleSpecific,
        is_deprecated: false,
    },
    Attribute {
        name: "aria-rowspan",
        is_state: false,
        value_type: ValueType::Integer,
        values: &[],
        default: None,
        scope: Scope::RoleSpecific,
        is_deprecated: false,
    },
    Attribute {
        name: "aria-selected",
        is_state: true,
        value_type: ValueType::TrueFalseUndefined,
        values: &["false", "true", "undefined"],
        default: Some("undefined"),
        scope: Scope::RoleSpecific,
        is_deprecated: false,
    },
    Attribute {
        name: "aria-setsize",
        is_state: false,
        value_type: ValueType::Integer,
        values: &[],
        default: None,
        scope: Scope::RoleSpecific,
        is_deprecated: false,
    },
    Attribute {
        name: "aria-sort",
        is_state: false,
        value_type: ValueType::Token,
        values: &["ascending", "descending", "none", "other"],
        default: Some("none"),
        scope: Scope::RoleSpecific,
        is_deprecated: false,
    },
    Attribute {
        name: "aria-valuemax",
        is_state: false,
        value_type: ValueType::Number,
        values: &[],
        default: None,
        scope: Scope::RoleSpecific,
        is_deprecated: false,
    },
    Attribute {
        name: "aria-valuemin",
        is_state: false,
        value_type: ValueType::Number,
        values: &[],
        default: None,
        scope: Scope::RoleSpecific,
        is_deprecated: false,
    },
    Attribute {
        name: "aria-valuenow",
        is_state: false,
        value_type: ValueType::Number,
        values: &[],
        default: None,
        scope: Scope::RoleSpecific,
        is_deprecated: false,
    },
    Attribute {
        name: "aria-valuetext",
        is_state: false,
        value_type: ValueType::String,
        values: &[],
        default: None,
        scope: Scope::RoleSpecific,
        is_deprecated: false,
    },
];
