//! The characteristics table of every WAI-ARIA 1.2 role, extracted from
//! `index.html` of w3c/aria's `2023-06_REC` branch (commit `66caad8`).
//! Inherited states, properties and default values are resolved the way the
//! spec's own `common/script/aria.js` renders them: a role's own entry
//! overrides its superclasses'. `none` repeats `presentation`, whose synonym
//! it is and which holds the definition.

use super::roles::{NameFrom, OwnedElement, Role};

pub(super) const ROLES: &[Role] = &[
    Role {
        name: "alert",
        is_abstract: false,
        superclasses: &["section"],
        ancestors: &["section", "structure", "roletype"],
        required_context: &[],
        required_owned: &[],
        name_from: &[NameFrom::Author],
        children_presentational: false,
        specific_attributes: &[],
        prohibited_attributes: &[],
        deprecated_attributes: &[
            "aria-disabled",
            "aria-dropeffect",
            "aria-errormessage",
            "aria-grabbed",
            "aria-haspopup",
            "aria-invalid",
        ],
        default_values: &[("aria-live", "assertive"), ("aria-atomic", "true")],
    },
    Role {
        name: "alertdialog",
        is_abstract: false,
        superclasses: &["alert", "dialog"],
        ancestors: &[
            "alert",
            "section",
            "structure",
            "roletype",
            "dialog",
            "window",
        ],
        required_context: &[],
        required_owned: &[],
        name_from: &[NameFrom::Author],
        children_presentational: false,
        specific_attributes: &["aria-modal"],
        prohibited_attributes: &[],
        deprecated_attributes: &[
            "aria-disabled",
            "aria-dropeffect",
            "aria-errormessage",
            "aria-grabbed",
            "aria-haspopup",
            "aria-invalid",
        ],
        default_values: &[("aria-live", "assertive"), ("aria-atomic", "true")],
    },
    Role {
        name: "application",
        is_abstract: false,
        superclasses: &["structure"],
        ancestors: &["structure", "roletype"],
        required_context: &[],
        required_owned: &[],
        name_from: &[NameFrom::Author],
        children_presentational: false,
        specific_attributes: &["aria-activedescendant", "aria-expanded"],
        prohibited_attributes: &[],
        deprecated_attributes: &["aria-dropeffect", "aria-grabbed"],
        default_values: &[],
    },
    Role {
        name: "article",
        is_abstract: false,
        superclasses: &["document"],
        ancestors: &["document", "structure", "roletype"],
        required_context: &[],
        required_owned: &[],
        name_from: &[NameFrom::Author],
        children_presentational: false,
        specific_attributes: &["aria-posinset", "aria-setsize"],
        prohibited_attributes: &[],
        deprecated_attributes: &[
            "aria-disabled",
            "aria-dropeffect",
            "aria-errormessage",
            "aria-grabbed",
            "aria-haspopup",
            "aria-invalid",
        ],
        default_values: &[],
    },
    Role {
        name: "banner",
        is_abstract: false,
        superclasses: &["landmark"],
        ancestors: &["landmark", "section", "structure", "roletype"],
        required_context: &[],
        required_owned: &[],
        name_from: &[NameFrom::Author],
        children_presentational: false,
        specific_attributes: &[],
        prohibited_attributes: &[],
        deprecated_attributes: &[
            "aria-disabled",
            "aria-dropeffect",
            "aria-errormessage",
            "aria-grabbed",
            "aria-haspopup",
            "aria-invalid",
        ],
        default_values: &[],
    },
    Role {
        name: "blockquote",
        is_abstract: false,
        superclasses: &["section"],
        ancestors: &["section", "structure", "roletype"],
        required_context: &[],
        required_owned: &[],
        name_from: &[NameFrom::Author],
        children_presentational: false,
        specific_attributes: &[],
        prohibited_attributes: &[],
        deprecated_attributes: &[
            "aria-disabled",
            "aria-dropeffect",
            "aria-errormessage",
            "aria-grabbed",
            "aria-haspopup",
            "aria-invalid",
        ],
        default_values: &[],
    },
    Role {
        name: "button",
        is_abstract: false,
        superclasses: &["command"],
        ancestors: &["command", "widget", "roletype"],
        required_context: &[],
        required_owned: &[],
        name_from: &[NameFrom::Author, NameFrom::Contents],
        children_presentational: true,
        specific_attributes: &["aria-expanded", "aria-pressed"],
        prohibited_attributes: &[],
        deprecated_attributes: &[
            "aria-dropeffect",
            "aria-errormessage",
            "aria-grabbed",
            "aria-invalid",
        ],
        default_values: &[],
    },
    Role {
        name: "caption",
        is_abstract: false,
        superclasses: &["section"],
        ancestors: &["section", "structure", "roletype"],
        required_context: &["figure", "grid", "table", "treegrid"],
        required_owned: &[],
        name_from: &[NameFrom::Prohibited],
        children_presentational: false,
        specific_attributes: &[],
        prohibited_attributes: &["aria-label", "aria-labelledby"],
        deprecated_attributes: &[
            "aria-disabled",
            "aria-dropeffect",
            "aria-errormessage",
            "aria-grabbed",
            "aria-haspopup",
            "aria-invalid",
        ],
        default_values: &[],
    },
    Role {
        name: "cell",
        is_abstract: false,
        superclasses: &["section"],
        ancestors: &["section", "structure", "roletype"],
        required_context: &["row"],
        required_owned: &[],
        name_from: &[NameFrom::Author, NameFrom::Contents],
        children_presentational: false,
        specific_attributes: &[
            "aria-colindex",
            "aria-colspan",
            "aria-rowindex",
            "aria-rowspan",
        ],
        prohibited_attributes: &[],
        deprecated_attributes: &[
            "aria-disabled",
            "aria-dropeffect",
            "aria-errormessage",
            "aria-grabbed",
            "aria-haspopup",
            "aria-invalid",
        ],
        default_values: &[],
    },
    Role {
        name: "checkbox",
        is_abstract: false,
        superclasses: &["input"],
        ancestors: &["input", "widget", "roletype"],
        required_context: &[],
        required_owned: &[],
        name_from: &[NameFrom::Author, NameFrom::Contents],
        children_presentational: true,
        specific_attributes: &[
            "aria-checked",
            "aria-expanded",
            "aria-readonly",
            "aria-required",
        ],
        prohibited_attributes: &[],
        deprecated_attributes: &["aria-dropeffect", "aria-grabbed", "aria-haspopup"],
        default_values: &[],
    },
    Role {
        name: "code",
        is_abstract: false,
        superclasses: &["section"],
        ancestors: &["section", "structure", "roletype"],
        required_context: &[],
        required_owned: &[],
        name_from: &[NameFrom::Prohibited],
        children_presentational: false,
        specific_attributes: &[],
        prohibited_attributes: &["aria-label", "aria-labelledby"],
        deprecated_attributes: &[
            "aria-disabled",
            "aria-dropeffect",
            "aria-errormessage",
            "aria-grabbed",
            "aria-haspopup",
            "aria-invalid",
        ],
        default_values: &[],
    },
    Role {
        name: "columnheader",
        is_abstract: false,
        superclasses: &["cell", "gridcell", "sectionhead"],
        ancestors: &[
            "cell",
            "section",
            "structure",
            "roletype",
            "gridcell",
            "widget",
            "sectionhead",
        ],
        required_context: &["row"],
        required_owned: &[],
        name_from: &[NameFrom::Author, NameFrom::Contents],
        children_presentational: false,
        specific_attributes: &[
            "aria-colindex",
            "aria-colspan",
            "aria-expanded",
            "aria-readonly",
            "aria-required",
            "aria-rowindex",
            "aria-rowspan",
            "aria-selected",
            "aria-sort",
        ],
        prohibited_attributes: &[],
        deprecated_attributes: &[
            "aria-disabled",
            "aria-dropeffect",
            "aria-errormessage",
            "aria-grabbed",
            "aria-haspopup",
            "aria-invalid",
        ],
        default_values: &[],
    },
    Role {
        name: "combobox",
        is_abstract: false,
        superclasses: &["input"],
        ancestors: &["input", "widget", "roletype"],
        required_context: &[],
        required_owned: &[],
        name_from: &[NameFrom::Author],
        children_presentational: false,
        specific_attributes: &[
            "aria-activedescendant",
            "aria-autocomplete",
            "aria-expanded",
            "aria-readonly",
            "aria-required",
        ],
        prohibited_attributes: &[],
        deprecated_attributes: &["aria-dropeffect", "aria-grabbed"],
        default_values: &[("aria-haspopup", "listbox")],
    },
    Role {
        name: "command",
        is_abstract: true,
        superclasses: &["widget"],
        ancestors: &["widget", "roletype"],
        required_context: &[],
        required_owned: &[],
        name_from: &[NameFrom::Author],
        children_presentational: false,
        specific_attributes: &[],
        prohibited_attributes: &[],
        deprecated_attributes: &[
            "aria-disabled",
            "aria-dropeffect",
            "aria-errormessage",
            "aria-grabbed",
            "aria-haspopup",
            "aria-invalid",
        ],
        default_values: &[],
    },
    Role {
        name: "complementary",
        is_abstract: false,
        superclasses: &["landmark"],
        ancestors: &["landmark", "section", "structure", "roletype"],
        required_context: &[],
        required_owned: &[],
        name_from: &[NameFrom::Author],
        children_presentational: false,
        specific_attributes: &[],
        prohibited_attributes: &[],
        deprecated_attributes: &[
            "aria-disabled",
            "aria-dropeffect",
            "aria-errormessage",
            "aria-grabbed",
            "aria-haspopup",
            "aria-invalid",
        ],
        default_values: &[],
    },
    Role {
        name: "composite",
        is_abstract: true,
        superclasses: &["widget"],
        ancestors: &["widget", "roletype"],
        required_context: &[],
        required_owned: &[],
        name_from: &[NameFrom::Author],
        children_presentational: false,
        specific_attributes: &["aria-activedescendant"],
        prohibited_attributes: &[],
        deprecated_attributes: &[
            "aria-dropeffect",
            "aria-errormessage",
            "aria-grabbed",
            "aria-haspopup",
            "aria-invalid",
        ],
        default_values: &[],
    },
    Role {
        name: "contentinfo",
        is_abstract: false,
        superclasses: &["landmark"],
        ancestors: &["landmark", "section", "structure", "roletype"],
        required_context: &[],
        required_owned: &[],
        name_from: &[NameFrom::Author],
        children_presentational: false,
        specific_attributes: &[],
        prohibited_attributes: &[],
        deprecated_attributes: &[
            "aria-disabled",
            "aria-dropeffect",
            "aria-errormessage",
            "aria-grabbed",
            "aria-haspopup",
            "aria-invalid",
        ],
        default_values: &[],
    },
    Role {
        name: "definition",
        is_abstract: false,
        superclasses: &["section"],
        ancestors: &["section", "structure", "roletype"],
        required_context: &[],
        required_owned: &[],
        name_from: &[NameFrom::Author],
        children_presentational: false,
        specific_attributes: &[],
        prohibited_attributes: &[],
        deprecated_attributes: &[
            "aria-disabled",
            "aria-dropeffect",
            "aria-errormessage",
            "aria-grabbed",
            "aria-haspopup",
            "aria-invalid",
        ],
        default_values: &[],
    },
    Role {
        name: "deletion",
        is_abstract: false,
        superclasses: &["section"],
        ancestors: &["section", "structure", "roletype"],
        required_context: &[],
        required_owned: &[],
        name_from: &[NameFrom::Prohibited],
        children_presentational: false,
        specific_attributes: &[],
        prohibited_attributes: &["aria-label", "aria-labelledby"],
        deprecated_attributes: &[
            "aria-disabled",
            "aria-dropeffect",
            "aria-errormessage",
            "aria-grabbed",
            "aria-haspopup",
            "aria-invalid",
        ],
        default_values: &[],
    },
    Role {
        name: "dialog",
        is_abstract: false,
        superclasses: &["window"],
        ancestors: &["window", "roletype"],
        required_context: &[],
        required_owned: &[],
        name_from: &[NameFrom::Author],
        children_presentational: false,
        specific_attributes: &["aria-modal"],
        prohibited_attributes: &[],
        deprecated_attributes: &[
            "aria-disabled",
            "aria-dropeffect",
            "aria-errormessage",
            "aria-grabbed",
            "aria-haspopup",
            "aria-invalid",
        ],
        default_values: &[],
    },
    Role {
        name: "directory",
        is_abstract: false,
        superclasses: &["list"],
        ancestors: &["list", "section", "structure", "roletype"],
        required_context: &[],
        required_owned: &[],
        name_from: &[NameFrom::Author],
        children_presentational: false,
        specific_attributes: &[],
        prohibited_attributes: &[],
        deprecated_attributes: &[
            "aria-disabled",
            "aria-dropeffect",
            "aria-errormessage",
            "aria-grabbed",
            "aria-haspopup",
            "aria-invalid",
        ],
        default_values: &[],
    },
    Role {
        name: "document",
        is_abstract: false,
        superclasses: &["structure"],
        ancestors: &["structure", "roletype"],
        required_context: &[],
        required_owned: &[],
        name_from: &[NameFrom::Author],
        children_presentational: false,
        specific_attributes: &[],
        prohibited_attributes: &[],
        deprecated_attributes: &[
            "aria-disabled",
            "aria-dropeffect",
            "aria-errormessage",
            "aria-grabbed",
            "aria-haspopup",
            "aria-invalid",
        ],
        default_values: &[],
    },
    Role {
        name: "emphasis",
        is_abstract: false,
        superclasses: &["section"],
        ancestors: &["section", "structure", "roletype"],
        required_context: &[],
        required_owned: &[],
        name_from: &[NameFrom::Prohibited],
        children_presentational: false,
        specific_attributes: &[],
        prohibited_attributes: &["aria-label", "aria-labelledby"],
        deprecated_attributes: &[
            "aria-disabled",
            "aria-dropeffect",
            "aria-errormessage",
            "aria-grabbed",
            "aria-haspopup",
            "aria-invalid",
        ],
        default_values: &[],
    },
    Role {
        name: "feed",
        is_abstract: false,
        superclasses: &["list"],
        ancestors: &["list", "section", "structure", "roletype"],
        required_context: &[],
        required_owned: &[OwnedElement {
            role: "article",
            via: None,
        }],
        name_from: &[NameFrom::Author],
        children_presentational: false,
        specific_attributes: &[],
        prohibited_attributes: &[],
        deprecated_attributes: &[
            "aria-disabled",
            "aria-dropeffect",
            "aria-errormessage",
            "aria-grabbed",
            "aria-haspopup",
            "aria-invalid",
        ],
        default_values: &[],
    },
    Role {
        name: "figure",
        is_abstract: false,
        superclasses: &["section"],
        ancestors: &["section", "structure", "roletype"],
        required_context: &[],
        required_owned: &[],
        name_from: &[NameFrom::Author],
        children_presentational: false,
        specific_attributes: &[],
        prohibited_attributes: &[],
        deprecated_attributes: &[
            "aria-disabled",
            "aria-dropeffect",
            "aria-errormessage",
            "aria-grabbed",
            "aria-haspopup",
            "aria-invalid",
        ],
        default_values: &[],
    },
    Role {
        name: "form",
        is_abstract: false,
        superclasses: &["landmark"],
        ancestors: &["landmark", "section", "structure", "roletype"],
        required_context: &[],
        required_owned: &[],
        name_from: &[NameFrom::Author],
        children_presentational: false,
        specific_attributes: &[],
        prohibited_attributes: &[],
        deprecated_attributes: &[
            "aria-disabled",
            "aria-dropeffect",
            "aria-errormessage",
            "aria-grabbed",
            "aria-haspopup",
            "aria-invalid",
        ],
        default_values: &[],
    },
    Role {
        name: "generic",
        is_abstract: false,
        superclasses: &["structure"],
        ancestors: &["structure", "roletype"],
        required_context: &[],
        required_owned: &[],
        name_from: &[NameFrom::Prohibited],
        children_presentational: false,
        specific_attributes: &[],
        prohibited_attributes: &["aria-label", "aria-labelledby", "aria-roledescription"],
        deprecated_attributes: &[
            "aria-disabled",
            "aria-dropeffect",
            "aria-errormessage",
            "aria-grabbed",
            "aria-haspopup",
            "aria-invalid",
        ],
        default_values: &[],
    },
    Role {
        name: "grid",
        is_abstract: false,
        superclasses: &["composite", "table"],
        ancestors: &[
            "composite",
            "widget",
            "roletype",
            "table",
            "section",
            "structure",
        ],
        required_context: &[],
        required_owned: &[
            OwnedElement {
                role: "row",
                via: None,
            },
            OwnedElement {
                role: "row",
                via: Some("rowgroup"),
            },
        ],
        name_from: &[NameFrom::Author],
        children_presentational: false,
        specific_attributes: &[
            "aria-activedescendant",
            "aria-colcount",
            "aria-multiselectable",
            "aria-readonly",
            "aria-rowcount",
        ],
        prohibited_attributes: &[],
        deprecated_attributes: &[
            "aria-dropeffect",
            "aria-errormessage",
            "aria-grabbed",
            "aria-haspopup",
            "aria-invalid",
        ],
        default_values: &[],
    },
    Role {
        name: "gridcell",
        is_abstract: false,
        superclasses: &["cell", "widget"],
        ancestors: &["cell", "section", "structure", "roletype", "widget"],
        required_context: &["row"],
        required_owned: &[],
        name_from: &[NameFrom::Author, NameFrom::Contents],
        children_presentational: false,
        specific_attributes: &[
            "aria-colindex",
            "aria-colspan",
            "aria-expanded",
            "aria-readonly",
            "aria-required",
            "aria-rowindex",
            "aria-rowspan",
            "aria-selected",
        ],
        prohibited_attributes: &[],
        deprecated_attributes: &["aria-dropeffect", "aria-grabbed"],
        default_values: &[],
    },
    Role {
        name: "group",
        is_abstract: false,
        superclasses: &["section"],
        ancestors: &["section", "structure", "roletype"],
        required_context: &[],
        required_owned: &[],
        name_from: &[NameFrom::Author],
        children_presentational: false,
        specific_attributes: &["aria-activedescendant"],
        prohibited_attributes: &[],
        deprecated_attributes: &[
            "aria-dropeffect",
            "aria-errormessage",
            "aria-grabbed",
            "aria-haspopup",
            "aria-invalid",
        ],
        default_values: &[],
    },
    Role {
        name: "heading",
        is_abstract: false,
        superclasses: &["sectionhead"],
        ancestors: &["sectionhead", "structure", "roletype"],
        required_context: &[],
        required_owned: &[],
        name_from: &[NameFrom::Author, NameFrom::Contents],
        children_presentational: false,
        specific_attributes: &["aria-level"],
        prohibited_attributes: &[],
        deprecated_attributes: &[
            "aria-disabled",
            "aria-dropeffect",
            "aria-errormessage",
            "aria-grabbed",
            "aria-haspopup",
            "aria-invalid",
        ],
        default_values: &[],
    },
    Role {
        name: "img",
        is_abstract: false,
        superclasses: &["section"],
        ancestors: &["section", "structure", "roletype"],
        required_context: &[],
        required_owned: &[],
        name_from: &[NameFrom::Author],
        children_presentational: true,
        specific_attributes: &[],
        prohibited_attributes: &[],
        deprecated_attributes: &[
            "aria-disabled",
            "aria-dropeffect",
            "aria-errormessage",
            "aria-grabbed",
            "aria-haspopup",
            "aria-invalid",
        ],
        default_values: &[],
    },
    Role {
        name: "input",
        is_abstract: true,
        superclasses: &["widget"],
        ancestors: &["widget", "roletype"],
        required_context: &[],
        required_owned: &[],
        name_from: &[NameFrom::Author],
        children_presentational: false,
        specific_attributes: &[],
        prohibited_attributes: &[],
        deprecated_attributes: &[
            "aria-dropeffect",
            "aria-errormessage",
            "aria-grabbed",
            "aria-haspopup",
            "aria-invalid",
        ],
        default_values: &[],
    },
    Role {
        name: "insertion",
        is_abstract: false,
        superclasses: &["section"],
        ancestors: &["section", "structure", "roletype"],
        required_context: &[],
        required_owned: &[],
        name_from: &[NameFrom::Prohibited],
        children_presentational: false,
        specific_attributes: &[],
        prohibited_attributes: &["aria-label", "aria-labelledby"],
        deprecated_attributes: &[
            "aria-disabled",
            "aria-dropeffect",
            "aria-errormessage",
            "aria-grabbed",
            "aria-haspopup",
            "aria-invalid",
        ],
        default_values: &[],
    },
    Role {
        name: "landmark",
        is_abstract: true,
        superclasses: &["section"],
        ancestors: &["section", "structure", "roletype"],
        required_context: &[],
        required_owned: &[],
        name_from: &[NameFrom::Author],
        children_presentational: false,
        specific_attributes: &[],
        prohibited_attributes: &[],
        deprecated_attributes: &[
            "aria-disabled",
            "aria-dropeffect",
            "aria-errormessage",
            "aria-grabbed",
            "aria-haspopup",
            "aria-invalid",
        ],
        default_values: &[],
    },
    Role {
        name: "link",
        is_abstract: false,
        superclasses: &["command"],
        ancestors: &["command", "widget", "roletype"],
        required_context: &[],
        required_owned: &[],
        name_from: &[NameFrom::Author, NameFrom::Contents],
        children_presentational: false,
        specific_attributes: &["aria-expanded"],
        prohibited_attributes: &[],
        deprecated_attributes: &[
            "aria-dropeffect",
            "aria-errormessage",
            "aria-grabbed",
            "aria-invalid",
        ],
        default_values: &[],
    },
    Role {
        name: "list",
        is_abstract: false,
        superclasses: &["section"],
        ancestors: &["section", "structure", "roletype"],
        required_context: &[],
        required_owned: &[OwnedElement {
            role: "listitem",
            via: None,
        }],
        name_from: &[NameFrom::Author],
        children_presentational: false,
        specific_attributes: &[],
        prohibited_attributes: &[],
        deprecated_attributes: &[
            "aria-disabled",
            "aria-dropeffect",
            "aria-errormessage",
            "aria-grabbed",
            "aria-haspopup",
            "aria-invalid",
        ],
        default_values: &[],
    },
    Role {
        name: "listbox",
        is_abstract: false,
        superclasses: &["select"],
        ancestors: &[
            "select",
            "composite",
            "widget",
            "roletype",
            "group",
            "section",
            "structure",
        ],
        required_context: &[],
        required_owned: &[
            OwnedElement {
                role: "option",
                via: Some("group"),
            },
            OwnedElement {
                role: "option",
                via: None,
            },
        ],
        name_from: &[NameFrom::Author],
        children_presentational: false,
        specific_attributes: &[
            "aria-activedescendant",
            "aria-expanded",
            "aria-multiselectable",
            "aria-orientation",
            "aria-readonly",
            "aria-required",
        ],
        prohibited_attributes: &[],
        deprecated_attributes: &["aria-dropeffect", "aria-grabbed", "aria-haspopup"],
        default_values: &[("aria-orientation", "vertical")],
    },
    Role {
        name: "listitem",
        is_abstract: false,
        superclasses: &["section"],
        ancestors: &["section", "structure", "roletype"],
        required_context: &["directory", "list"],
        required_owned: &[],
        name_from: &[NameFrom::Author],
        children_presentational: false,
        specific_attributes: &["aria-level", "aria-posinset", "aria-setsize"],
        prohibited_attributes: &[],
        deprecated_attributes: &[
            "aria-disabled",
            "aria-dropeffect",
            "aria-errormessage",
            "aria-grabbed",
            "aria-haspopup",
            "aria-invalid",
        ],
        default_values: &[],
    },
    Role {
        name: "log",
        is_abstract: false,
        superclasses: &["section"],
        ancestors: &["section", "structure", "roletype"],
        required_context: &[],
        required_owned: &[],
        name_from: &[NameFrom::Author],
        children_presentational: false,
        specific_attributes: &[],
        prohibited_attributes: &[],
        deprecated_attributes: &[
            "aria-disabled",
            "aria-dropeffect",
            "aria-errormessage",
            "aria-grabbed",
            "aria-haspopup",
            "aria-invalid",
        ],
        default_values: &[("aria-live", "polite")],
    },
    Role {
        name: "main",
        is_abstract: false,
        superclasses: &["landmark"],
        ancestors: &["landmark", "section", "structure", "roletype"],
        required_context: &[],
        required_owned: &[],
        name_from: &[NameFrom::Author],
        children_presentational: false,
        specific_attributes: &[],
        prohibited_attributes: &[],
        deprecated_attributes: &[
            "aria-disabled",
            "aria-dropeffect",
            "aria-errormessage",
            "aria-grabbed",
            "aria-haspopup",
            "aria-invalid",
        ],
        default_values: &[],
    },
    Role {
        name: "marquee",
        is_abstract: false,
        superclasses: &["section"],
        ancestors: &["section", "structure", "roletype"],
        required_context: &[],
        required_owned: &[],
        name_from: &[NameFrom::Author],
        children_presentational: false,
        specific_attributes: &[],
        prohibited_attributes: &[],
        deprecated_attributes: &[
            "aria-disabled",
            "aria-dropeffect",
            "aria-errormessage",
            "aria-grabbed",
            "aria-haspopup",
            "aria-invalid",
        ],
        default_values: &[],
    },
    Role {
        name: "math",
        is_abstract: false,
        superclasses: &["section"],
        ancestors: &["section", "structure", "roletype"],
        required_context: &[],
        required_owned: &[],
        name_from: &[NameFrom::Author],
        children_presentational: false,
        specific_attributes: &[],
        prohibited_attributes: &[],
        deprecated_attributes: &[
            "aria-disabled",
            "aria-dropeffect",
            "aria-errormessage",
            "aria-grabbed",
            "aria-haspopup",
            "aria-invalid",
        ],
        default_values: &[],
    },
    Role {
        name: "menu",
        is_abstract: false,
        superclasses: &["select"],
        ancestors: &[
            "select",
            "composite",
            "widget",
            "roletype",
            "group",
            "section",
            "structure",
        ],
        required_context: &[],
        required_owned: &[
            OwnedElement {
                role: "menuitem",
                via: Some("group"),
            },
            OwnedElement {
                role: "menuitemradio",
                via: Some("group"),
            },
            OwnedElement {
                role: "menuitemcheckbox",
                via: Some("group"),
            },
            OwnedElement {
                role: "menuitem",
                via: None,
            },
            OwnedElement {
                role: "menuitemcheckbox",
                via: None,
            },
            OwnedElement {
                role: "menuitemradio",
                via: None,
            },
        ],
        name_from: &[NameFrom::Author],
        children_presentational: false,
        specific_attributes: &["aria-activedescendant", "aria-orientation"],
        prohibited_attributes: &[],
        deprecated_attributes: &[
            "aria-dropeffect",
            "aria-errormessage",
            "aria-grabbed",
            "aria-haspopup",
            "aria-invalid",
        ],
        default_values: &[("aria-orientation", "vertical")],
    },
    Role {
        name: "menubar",
        is_abstract: false,
        superclasses: &["menu"],
        ancestors: &[
            "menu",
            "select",
            "composite",
            "widget",
            "roletype",
            "group",
            "section",
            "structure",
        ],
        required_context: &[],
        required_owned: &[
            OwnedElement {
                role: "menuitem",
                via: Some("group"),
            },
            OwnedElement {
                role: "menuitemradio",
                via: Some("group"),
            },
            OwnedElement {
                role: "menuitemcheckbox",
                via: Some("group"),
            },
            OwnedElement {
                role: "menuitem",
                via: None,
            },
            OwnedElement {
                role: "menuitemcheckbox",
                via: None,
            },
            OwnedElement {
                role: "menuitemradio",
                via: None,
            },
        ],
        name_from: &[NameFrom::Author],
        children_presentational: false,
        specific_attributes: &["aria-activedescendant", "aria-orientation"],
        prohibited_attributes: &[],
        deprecated_attributes: &[
            "aria-dropeffect",
            "aria-errormessage",
            "aria-grabbed",
            "aria-haspopup",
            "aria-invalid",
        ],
        default_values: &[("aria-orientation", "horizontal")],
    },
    Role {
        name: "menuitem",
        is_abstract: false,
        superclasses: &["command"],
        ancestors: &["command", "widget", "roletype"],
        required_context: &["group", "menu", "menubar"],
        required_owned: &[],
        name_from: &[NameFrom::Author, NameFrom::Contents],
        children_presentational: false,
        specific_attributes: &["aria-expanded", "aria-posinset", "aria-setsize"],
        prohibited_attributes: &[],
        deprecated_attributes: &[
            "aria-dropeffect",
            "aria-errormessage",
            "aria-grabbed",
            "aria-invalid",
        ],
        default_values: &[],
    },
    Role {
        name: "menuitemcheckbox",
        is_abstract: false,
        superclasses: &["menuitem"],
        ancestors: &["menuitem", "command", "widget", "roletype"],
        required_context: &["group", "menu", "menubar"],
        required_owned: &[],
        name_from: &[NameFrom::Author, NameFrom::Contents],
        children_presentational: true,
        specific_attributes: &[
            "aria-checked",
            "aria-expanded",
            "aria-posinset",
            "aria-setsize",
        ],
        prohibited_attributes: &[],
        deprecated_attributes: &[
            "aria-dropeffect",
            "aria-errormessage",
            "aria-grabbed",
            "aria-invalid",
        ],
        default_values: &[],
    },
    Role {
        name: "menuitemradio",
        is_abstract: false,
        superclasses: &["menuitemcheckbox"],
        ancestors: &[
            "menuitemcheckbox",
            "menuitem",
            "command",
            "widget",
            "roletype",
        ],
        required_context: &["group", "menu", "menubar"],
        required_owned: &[],
        name_from: &[NameFrom::Author, NameFrom::Contents],
        children_presentational: true,
        specific_attributes: &[
            "aria-checked",
            "aria-expanded",
            "aria-posinset",
            "aria-setsize",
        ],
        prohibited_attributes: &[],
        deprecated_attributes: &[
            "aria-dropeffect",
            "aria-errormessage",
            "aria-grabbed",
            "aria-invalid",
        ],
        default_values: &[],
    },
    Role {
        name: "meter",
        is_abstract: false,
        superclasses: &["range"],
        ancestors: &["range", "structure", "roletype"],
        required_context: &[],
        required_owned: &[],
        name_from: &[NameFrom::Author],
        children_presentational: true,
        specific_attributes: &[
            "aria-valuemax",
            "aria-valuemin",
            "aria-valuenow",
            "aria-valuetext",
        ],
        prohibited_attributes: &[],
        deprecated_attributes: &[
            "aria-disabled",
            "aria-dropeffect",
            "aria-errormessage",
            "aria-grabbed",
            "aria-haspopup",
            "aria-invalid",
        ],
        default_values: &[("aria-valuemin", "0"), ("aria-valuemax", "100")],
    },
    Role {
        name: "navigation",
        is_abstract: false,
        superclasses: &["landmark"],
        ancestors: &["landmark", "section", "structure", "roletype"],
        required_context: &[],
        required_owned: &[],
        name_from: &[NameFrom::Author],
        children_presentational: false,
        specific_attributes: &[],
        prohibited_attributes: &[],
        deprecated_attributes: &[
            "aria-disabled",
            "aria-dropeffect",
            "aria-errormessage",
            "aria-grabbed",
            "aria-haspopup",
            "aria-invalid",
        ],
        default_values: &[],
    },
    Role {
        name: "none",
        is_abstract: false,
        superclasses: &["structure"],
        ancestors: &["structure", "roletype"],
        required_context: &[],
        required_owned: &[],
        name_from: &[NameFrom::Prohibited],
        children_presentational: false,
        specific_attributes: &[],
        prohibited_attributes: &["aria-label", "aria-labelledby"],
        deprecated_attributes: &[
            "aria-disabled",
            "aria-dropeffect",
            "aria-errormessage",
            "aria-grabbed",
            "aria-haspopup",
            "aria-invalid",
        ],
        default_values: &[],
    },
    Role {
        name: "note",
        is_abstract: false,
        superclasses: &["section"],
        ancestors: &["section", "structure", "roletype"],
        required_context: &[],
        required_owned: &[],
        name_from: &[NameFrom::Author],
        children_presentational: false,
        specific_attributes: &[],
        prohibited_attributes: &[],
        deprecated_attributes: &[
            "aria-disabled",
            "aria-dropeffect",
            "aria-errormessage",
            "aria-grabbed",
            "aria-haspopup",
            "aria-invalid",
        ],
        default_values: &[],
    },
    Role {
        name: "option",
        is_abstract: false,
        superclasses: &["input"],
        ancestors: &["input", "widget", "roletype"],
        required_context: &["group", "listbox"],
        required_owned: &[],
        name_from: &[NameFrom::Author, NameFrom::Contents],
        children_presentational: true,
        specific_attributes: &[
            "aria-checked",
            "aria-posinset",
            "aria-selected",
            "aria-setsize",
        ],
        prohibited_attributes: &[],
        deprecated_attributes: &[
            "aria-dropeffect",
            "aria-errormessage",
            "aria-grabbed",
            "aria-haspopup",
            "aria-invalid",
        ],
        default_values: &[("aria-selected", "false")],
    },
    Role {
        name: "paragraph",
        is_abstract: false,
        superclasses: &["section"],
        ancestors: &["section", "structure", "roletype"],
        required_context: &[],
        required_owned: &[],
        name_from: &[NameFrom::Prohibited],
        children_presentational: false,
        specific_attributes: &[],
        prohibited_attributes: &["aria-label", "aria-labelledby"],
        deprecated_attributes: &[
            "aria-disabled",
            "aria-dropeffect",
            "aria-errormessage",
            "aria-grabbed",
            "aria-haspopup",
            "aria-invalid",
        ],
        default_values: &[],
    },
    Role {
        name: "presentation",
        is_abstract: false,
        superclasses: &["structure"],
        ancestors: &["structure", "roletype"],
        required_context: &[],
        required_owned: &[],
        name_from: &[NameFrom::Prohibited],
        children_presentational: false,
        specific_attributes: &[],
        prohibited_attributes: &["aria-label", "aria-labelledby"],
        deprecated_attributes: &[
            "aria-disabled",
            "aria-dropeffect",
            "aria-errormessage",
            "aria-grabbed",
            "aria-haspopup",
            "aria-invalid",
        ],
        default_values: &[],
    },
    Role {
        name: "progressbar",
        is_abstract: false,
        superclasses: &["range", "widget"],
        ancestors: &["range", "structure", "roletype", "widget"],
        required_context: &[],
        required_owned: &[],
        name_from: &[NameFrom::Author],
        children_presentational: true,
        specific_attributes: &[
            "aria-valuemax",
            "aria-valuemin",
            "aria-valuenow",
            "aria-valuetext",
        ],
        prohibited_attributes: &[],
        deprecated_attributes: &[
            "aria-disabled",
            "aria-dropeffect",
            "aria-errormessage",
            "aria-grabbed",
            "aria-haspopup",
            "aria-invalid",
        ],
        default_values: &[("aria-valuemin", "0"), ("aria-valuemax", "100")],
    },
    Role {
        name: "radio",
        is_abstract: false,
        superclasses: &["input"],
        ancestors: &["input", "widget", "roletype"],
        required_context: &[],
        required_owned: &[],
        name_from: &[NameFrom::Author, NameFrom::Contents],
        children_presentational: true,
        specific_attributes: &["aria-checked", "aria-posinset", "aria-setsize"],
        prohibited_attributes: &[],
        deprecated_attributes: &[
            "aria-dropeffect",
            "aria-errormessage",
            "aria-grabbed",
            "aria-haspopup",
            "aria-invalid",
        ],
        default_values: &[],
    },
    Role {
        name: "radiogroup",
        is_abstract: false,
        superclasses: &["select"],
        ancestors: &[
            "select",
            "composite",
            "widget",
            "roletype",
            "group",
            "section",
            "structure",
        ],
        required_context: &[],
        required_owned: &[OwnedElement {
            role: "radio",
            via: None,
        }],
        name_from: &[NameFrom::Author],
        children_presentational: false,
        specific_attributes: &[
            "aria-activedescendant",
            "aria-orientation",
            "aria-readonly",
            "aria-required",
        ],
        prohibited_attributes: &[],
        deprecated_attributes: &["aria-dropeffect", "aria-grabbed", "aria-haspopup"],
        default_values: &[],
    },
    Role {
        name: "range",
        is_abstract: true,
        superclasses: &["structure"],
        ancestors: &["structure", "roletype"],
        required_context: &[],
        required_owned: &[],
        name_from: &[NameFrom::Author],
        children_presentational: false,
        specific_attributes: &[
            "aria-valuemax",
            "aria-valuemin",
            "aria-valuenow",
            "aria-valuetext",
        ],
        prohibited_attributes: &[],
        deprecated_attributes: &[
            "aria-disabled",
            "aria-dropeffect",
            "aria-errormessage",
            "aria-grabbed",
            "aria-haspopup",
            "aria-invalid",
        ],
        default_values: &[],
    },
    Role {
        name: "region",
        is_abstract: false,
        superclasses: &["landmark"],
        ancestors: &["landmark", "section", "structure", "roletype"],
        required_context: &[],
        required_owned: &[],
        name_from: &[NameFrom::Author],
        children_presentational: false,
        specific_attributes: &[],
        prohibited_attributes: &[],
        deprecated_attributes: &[
            "aria-disabled",
            "aria-dropeffect",
            "aria-errormessage",
            "aria-grabbed",
            "aria-haspopup",
            "aria-invalid",
        ],
        default_values: &[],
    },
    Role {
        name: "roletype",
        is_abstract: true,
        superclasses: &[],
        ancestors: &[],
        required_context: &[],
        required_owned: &[],
        name_from: &[],
        children_presentational: false,
        specific_attributes: &[],
        prohibited_attributes: &[],
        deprecated_attributes: &[
            "aria-disabled",
            "aria-dropeffect",
            "aria-errormessage",
            "aria-grabbed",
            "aria-haspopup",
            "aria-invalid",
        ],
        default_values: &[],
    },
    Role {
        name: "row",
        is_abstract: false,
        superclasses: &["group", "widget"],
        ancestors: &["group", "section", "structure", "roletype", "widget"],
        required_context: &["grid", "rowgroup", "table", "treegrid"],
        required_owned: &[
            OwnedElement {
                role: "cell",
                via: None,
            },
            OwnedElement {
                role: "columnheader",
                via: None,
            },
            OwnedElement {
                role: "gridcell",
                via: None,
            },
            OwnedElement {
                role: "rowheader",
                via: None,
            },
        ],
        name_from: &[NameFrom::Author, NameFrom::Contents],
        children_presentational: false,
        specific_attributes: &[
            "aria-activedescendant",
            "aria-colindex",
            "aria-expanded",
            "aria-level",
            "aria-posinset",
            "aria-rowindex",
            "aria-selected",
            "aria-setsize",
        ],
        prohibited_attributes: &[],
        deprecated_attributes: &[
            "aria-dropeffect",
            "aria-errormessage",
            "aria-grabbed",
            "aria-haspopup",
            "aria-invalid",
        ],
        default_values: &[],
    },
    Role {
        name: "rowgroup",
        is_abstract: false,
        superclasses: &["structure"],
        ancestors: &["structure", "roletype"],
        required_context: &["grid", "table", "treegrid"],
        required_owned: &[OwnedElement {
            role: "row",
            via: None,
        }],
        name_from: &[NameFrom::Author],
        children_presentational: false,
        specific_attributes: &[],
        prohibited_attributes: &[],
        deprecated_attributes: &[
            "aria-disabled",
            "aria-dropeffect",
            "aria-errormessage",
            "aria-grabbed",
            "aria-haspopup",
            "aria-invalid",
        ],
        default_values: &[],
    },
    Role {
        name: "rowheader",
        is_abstract: false,
        superclasses: &["cell", "gridcell", "sectionhead"],
        ancestors: &[
            "cell",
            "section",
            "structure",
            "roletype",
            "gridcell",
            "widget",
            "sectionhead",
        ],
        required_context: &["row"],
        required_owned: &[],
        name_from: &[NameFrom::Author, NameFrom::Contents],
        children_presentational: false,
        specific_attributes: &[
            "aria-colindex",
            "aria-colspan",
            "aria-expanded",
            "aria-readonly",
            "aria-required",
            "aria-rowindex",
            "aria-rowspan",
            "aria-selected",
            "aria-sort",
        ],
        prohibited_attributes: &[],
        deprecated_attributes: &[
            "aria-disabled",
            "aria-dropeffect",
            "aria-errormessage",
            "aria-grabbed",
            "aria-haspopup",
            "aria-invalid",
        ],
        default_values: &[],
    },
    Role {
        name: "scrollbar",
        is_abstract: false,
        superclasses: &["range", "widget"],
        ancestors: &["range", "structure", "roletype", "widget"],
        required_context: &[],
        required_owned: &[],
        name_from: &[NameFrom::Author],
        children_presentational: true,
        specific_attributes: &[
            "aria-orientation",
            "aria-valuemax",
            "aria-valuemin",
            "aria-valuenow",
            "aria-valuetext",
        ],
        prohibited_attributes: &[],
        deprecated_attributes: &[
            "aria-dropeffect",
            "aria-errormessage",
            "aria-grabbed",
            "aria-haspopup",
            "aria-invalid",
        ],
        default_values: &[
            ("aria-orientation", "vertical"),
            ("aria-valuemin", "0"),
            ("aria-valuemax", "100"),
        ],
    },
    Role {
        name: "search",
        is_abstract: false,
        superclasses: &["landmark"],
        ancestors: &["landmark", "section", "structure", "roletype"],
        required_context: &[],
        required_owned: &[],
        name_from: &[NameFrom::Author],
        children_presentational: false,
        specific_attributes: &[],
        prohibited_attributes: &[],
        deprecated_attributes: &[
            "aria-disabled",
            "aria-dropeffect",
            "aria-errormessage",
            "aria-grabbed",
            "aria-haspopup",
            "aria-invalid",
        ],
        default_values: &[],
    },
    Role {
        name: "searchbox",
        is_abstract: false,
        superclasses: &["textbox"],
        ancestors: &["textbox", "input", "widget", "roletype"],
        required_context: &[],
        required_owned: &[],
        name_from: &[NameFrom::Author],
        children_presentational: false,
        specific_attributes: &[
            "aria-activedescendant",
            "aria-autocomplete",
            "aria-multiline",
            "aria-placeholder",
            "aria-readonly",
            "aria-required",
        ],
        prohibited_attributes: &[],
        deprecated_attributes: &["aria-dropeffect", "aria-grabbed"],
        default_values: &[],
    },
    Role {
        name: "section",
        is_abstract: true,
        superclasses: &["structure"],
        ancestors: &["structure", "roletype"],
        required_context: &[],
        required_owned: &[],
        name_from: &[],
        children_presentational: false,
        specific_attributes: &[],
        prohibited_attributes: &[],
        deprecated_attributes: &[
            "aria-disabled",
            "aria-dropeffect",
            "aria-errormessage",
            "aria-grabbed",
            "aria-haspopup",
            "aria-invalid",
        ],
        default_values: &[],
    },
    Role {
        name: "sectionhead",
        is_abstract: true,
        superclasses: &["structure"],
        ancestors: &["structure", "roletype"],
        required_context: &[],
        required_owned: &[],
        name_from: &[NameFrom::Author, NameFrom::Contents],
        children_presentational: false,
        specific_attributes: &[],
        prohibited_attributes: &[],
        deprecated_attributes: &[
            "aria-disabled",
            "aria-dropeffect",
            "aria-errormessage",
            "aria-grabbed",
            "aria-haspopup",
            "aria-invalid",
        ],
        default_values: &[],
    },
    Role {
        name: "select",
        is_abstract: true,
        superclasses: &["composite", "group"],
        ancestors: &[
            "composite",
            "widget",
            "roletype",
            "group",
            "section",
            "structure",
        ],
        required_context: &[],
        required_owned: &[],
        name_from: &[NameFrom::Author],
        children_presentational: false,
        specific_attributes: &["aria-activedescendant", "aria-orientation"],
        prohibited_attributes: &[],
        deprecated_attributes: &[
            "aria-dropeffect",
            "aria-errormessage",
            "aria-grabbed",
            "aria-haspopup",
            "aria-invalid",
        ],
        default_values: &[],
    },
    Role {
        name: "separator",
        is_abstract: false,
        superclasses: &["structure", "widget"],
        ancestors: &["structure", "roletype", "widget"],
        required_context: &[],
        required_owned: &[],
        name_from: &[NameFrom::Author],
        children_presentational: true,
        specific_attributes: &[
            "aria-orientation",
            "aria-valuemax",
            "aria-valuemin",
            "aria-valuenow",
            "aria-valuetext",
        ],
        prohibited_attributes: &[],
        deprecated_attributes: &[
            "aria-dropeffect",
            "aria-errormessage",
            "aria-grabbed",
            "aria-haspopup",
            "aria-invalid",
        ],
        default_values: &[
            ("aria-orientation", "horizontal"),
            ("aria-valuemin", "0"),
            ("aria-valuemax", "100"),
        ],
    },
    Role {
        name: "slider",
        is_abstract: false,
        superclasses: &["input", "range"],
        ancestors: &["input", "widget", "roletype", "range", "structure"],
        required_context: &[],
        required_owned: &[],
        name_from: &[NameFrom::Author],
        children_presentational: true,
        specific_attributes: &[
            "aria-orientation",
            "aria-readonly",
            "aria-valuemax",
            "aria-valuemin",
            "aria-valuenow",
            "aria-valuetext",
        ],
        prohibited_attributes: &[],
        deprecated_attributes: &["aria-dropeffect", "aria-grabbed"],
        default_values: &[
            ("aria-orientation", "horizontal"),
            ("aria-valuemin", "0"),
            ("aria-valuemax", "100"),
        ],
    },
    Role {
        name: "spinbutton",
        is_abstract: false,
        superclasses: &["composite", "input", "range"],
        ancestors: &[
            "composite",
            "widget",
            "roletype",
            "input",
            "range",
            "structure",
        ],
        required_context: &[],
        required_owned: &[],
        name_from: &[NameFrom::Author],
        children_presentational: false,
        specific_attributes: &[
            "aria-activedescendant",
            "aria-readonly",
            "aria-required",
            "aria-valuemax",
            "aria-valuemin",
            "aria-valuenow",
            "aria-valuetext",
        ],
        prohibited_attributes: &[],
        deprecated_attributes: &["aria-dropeffect", "aria-grabbed", "aria-haspopup"],
        default_values: &[("aria-valuenow", "0")],
    },
    Role {
        name: "status",
        is_abstract: false,
        superclasses: &["section"],
        ancestors: &["section", "structure", "roletype"],
        required_context: &[],
        required_owned: &[],
        name_from: &[NameFrom::Author],
        children_presentational: false,
        specific_attributes: &[],
        prohibited_attributes: &[],
        deprecated_attributes: &[
            "aria-disabled",
            "aria-dropeffect",
            "aria-errormessage",
            "aria-grabbed",
            "aria-haspopup",
            "aria-invalid",
        ],
        default_values: &[("aria-live", "polite"), ("aria-atomic", "true")],
    },
    Role {
        name: "strong",
        is_abstract: false,
        superclasses: &["section"],
        ancestors: &["section", "structure", "roletype"],
        required_context: &[],
        required_owned: &[],
        name_from: &[NameFrom::Prohibited],
        children_presentational: false,
        specific_attributes: &[],
        prohibited_attributes: &["aria-label", "aria-labelledby"],
        deprecated_attributes: &[
            "aria-disabled",
            "aria-dropeffect",
            "aria-errormessage",
            "aria-grabbed",
            "aria-haspopup",
            "aria-invalid",
        ],
        default_values: &[],
    },
    Role {
        name: "structure",
        is_abstract: true,
        superclasses: &["roletype"],
        ancestors: &["roletype"],
        required_context: &[],
        required_owned: &[],
        name_from: &[],
        children_presentational: false,
        specific_attributes: &[],
        prohibited_attributes: &[],
        deprecated_attributes: &[
            "aria-disabled",
            "aria-dropeffect",
            "aria-errormessage",
            "aria-grabbed",
            "aria-haspopup",
            "aria-invalid",
        ],
        default_values: &[],
    },
    Role {
        name: "subscript",
        is_abstract: false,
        superclasses: &["section"],
        ancestors: &["section", "structure", "roletype"],
        required_context: &[],
        required_owned: &[],
        name_from: &[NameFrom::Prohibited],
        children_presentational: false,
        specific_attributes: &[],
        prohibited_attributes: &["aria-label", "aria-labelledby"],
        deprecated_attributes: &[
            "aria-disabled",
            "aria-dropeffect",
            "aria-errormessage",
            "aria-grabbed",
            "aria-haspopup",
            "aria-invalid",
        ],
        default_values: &[],
    },
    Role {
        name: "superscript",
        is_abstract: false,
        superclasses: &["section"],
        ancestors: &["section", "structure", "roletype"],
        required_context: &[],
        required_owned: &[],
        name_from: &[NameFrom::Prohibited],
        children_presentational: false,
        specific_attributes: &[],
        prohibited_attributes: &["aria-label", "aria-labelledby"],
        deprecated_attributes: &[
            "aria-disabled",
            "aria-dropeffect",
            "aria-errormessage",
            "aria-grabbed",
            "aria-haspopup",
            "aria-invalid",
        ],
        default_values: &[],
    },
    Role {
        name: "switch",
        is_abstract: false,
        superclasses: &["checkbox"],
        ancestors: &["checkbox", "input", "widget", "roletype"],
        required_context: &[],
        required_owned: &[],
        name_from: &[NameFrom::Author, NameFrom::Contents],
        children_presentational: true,
        specific_attributes: &[
            "aria-checked",
            "aria-expanded",
            "aria-readonly",
            "aria-required",
        ],
        prohibited_attributes: &[],
        deprecated_attributes: &["aria-dropeffect", "aria-grabbed", "aria-haspopup"],
        default_values: &[],
    },
    Role {
        name: "tab",
        is_abstract: false,
        superclasses: &["sectionhead", "widget"],
        ancestors: &["sectionhead", "structure", "roletype", "widget"],
        required_context: &["tablist"],
        required_owned: &[],
        name_from: &[NameFrom::Author, NameFrom::Contents],
        children_presentational: true,
        specific_attributes: &[
            "aria-expanded",
            "aria-posinset",
            "aria-selected",
            "aria-setsize",
        ],
        prohibited_attributes: &[],
        deprecated_attributes: &[
            "aria-dropeffect",
            "aria-errormessage",
            "aria-grabbed",
            "aria-invalid",
        ],
        default_values: &[("aria-selected", "false")],
    },
    Role {
        name: "table",
        is_abstract: false,
        superclasses: &["section"],
        ancestors: &["section", "structure", "roletype"],
        required_context: &[],
        required_owned: &[
            OwnedElement {
                role: "row",
                via: None,
            },
            OwnedElement {
                role: "row",
                via: Some("rowgroup"),
            },
        ],
        name_from: &[NameFrom::Author],
        children_presentational: false,
        specific_attributes: &["aria-colcount", "aria-rowcount"],
        prohibited_attributes: &[],
        deprecated_attributes: &[
            "aria-disabled",
            "aria-dropeffect",
            "aria-errormessage",
            "aria-grabbed",
            "aria-haspopup",
            "aria-invalid",
        ],
        default_values: &[],
    },
    Role {
        name: "tablist",
        is_abstract: false,
        superclasses: &["composite"],
        ancestors: &["composite", "widget", "roletype"],
        required_context: &[],
        required_owned: &[OwnedElement {
            role: "tab",
            via: None,
        }],
        name_from: &[NameFrom::Author],
        children_presentational: false,
        specific_attributes: &[
            "aria-activedescendant",
            "aria-multiselectable",
            "aria-orientation",
        ],
        prohibited_attributes: &[],
        deprecated_attributes: &[
            "aria-dropeffect",
            "aria-errormessage",
            "aria-grabbed",
            "aria-haspopup",
            "aria-invalid",
        ],
        default_values: &[("aria-orientation", "horizontal")],
    },
    Role {
        name: "tabpanel",
        is_abstract: false,
        superclasses: &["section"],
        ancestors: &["section", "structure", "roletype"],
        required_context: &[],
        required_owned: &[],
        name_from: &[NameFrom::Author],
        children_presentational: false,
        specific_attributes: &[],
        prohibited_attributes: &[],
        deprecated_attributes: &[
            "aria-disabled",
            "aria-dropeffect",
            "aria-errormessage",
            "aria-grabbed",
            "aria-haspopup",
            "aria-invalid",
        ],
        default_values: &[],
    },
    Role {
        name: "term",
        is_abstract: false,
        superclasses: &["section"],
        ancestors: &["section", "structure", "roletype"],
        required_context: &[],
        required_owned: &[],
        name_from: &[NameFrom::Author],
        children_presentational: false,
        specific_attributes: &[],
        prohibited_attributes: &[],
        deprecated_attributes: &[
            "aria-disabled",
            "aria-dropeffect",
            "aria-errormessage",
            "aria-grabbed",
            "aria-haspopup",
            "aria-invalid",
        ],
        default_values: &[],
    },
    Role {
        name: "textbox",
        is_abstract: false,
        superclasses: &["input"],
        ancestors: &["input", "widget", "roletype"],
        required_context: &[],
        required_owned: &[],
        name_from: &[NameFrom::Author],
        children_presentational: false,
        specific_attributes: &[
            "aria-activedescendant",
            "aria-autocomplete",
            "aria-multiline",
            "aria-placeholder",
            "aria-readonly",
            "aria-required",
        ],
        prohibited_attributes: &[],
        deprecated_attributes: &["aria-dropeffect", "aria-grabbed"],
        default_values: &[],
    },
    Role {
        name: "time",
        is_abstract: false,
        superclasses: &["section"],
        ancestors: &["section", "structure", "roletype"],
        required_context: &[],
        required_owned: &[],
        name_from: &[NameFrom::Author],
        children_presentational: false,
        specific_attributes: &[],
        prohibited_attributes: &[],
        deprecated_attributes: &[
            "aria-disabled",
            "aria-dropeffect",
            "aria-errormessage",
            "aria-grabbed",
            "aria-haspopup",
            "aria-invalid",
        ],
        default_values: &[],
    },
    Role {
        name: "timer",
        is_abstract: false,
        superclasses: &["status"],
        ancestors: &["status", "section", "structure", "roletype"],
        required_context: &[],
        required_owned: &[],
        name_from: &[NameFrom::Author],
        children_presentational: false,
        specific_attributes: &[],
        prohibited_attributes: &[],
        deprecated_attributes: &[
            "aria-disabled",
            "aria-dropeffect",
            "aria-errormessage",
            "aria-grabbed",
            "aria-haspopup",
            "aria-invalid",
        ],
        default_values: &[("aria-live", "polite"), ("aria-atomic", "true")],
    },
    Role {
        name: "toolbar",
        is_abstract: false,
        superclasses: &["group"],
        ancestors: &["group", "section", "structure", "roletype"],
        required_context: &[],
        required_owned: &[],
        name_from: &[NameFrom::Author],
        children_presentational: false,
        specific_attributes: &["aria-activedescendant", "aria-orientation"],
        prohibited_attributes: &[],
        deprecated_attributes: &[
            "aria-dropeffect",
            "aria-errormessage",
            "aria-grabbed",
            "aria-haspopup",
            "aria-invalid",
        ],
        default_values: &[("aria-orientation", "horizontal")],
    },
    Role {
        name: "tooltip",
        is_abstract: false,
        superclasses: &["section"],
        ancestors: &["section", "structure", "roletype"],
        required_context: &[],
        required_owned: &[],
        name_from: &[NameFrom::Author, NameFrom::Contents],
        children_presentational: false,
        specific_attributes: &[],
        prohibited_attributes: &[],
        deprecated_attributes: &[
            "aria-disabled",
            "aria-dropeffect",
            "aria-errormessage",
            "aria-grabbed",
            "aria-haspopup",
            "aria-invalid",
        ],
        default_values: &[],
    },
    Role {
        name: "tree",
        is_abstract: false,
        superclasses: &["select"],
        ancestors: &[
            "select",
            "composite",
            "widget",
            "roletype",
            "group",
            "section",
            "structure",
        ],
        required_context: &[],
        required_owned: &[
            OwnedElement {
                role: "treeitem",
                via: Some("group"),
            },
            OwnedElement {
                role: "treeitem",
                via: None,
            },
        ],
        name_from: &[NameFrom::Author],
        children_presentational: false,
        specific_attributes: &[
            "aria-activedescendant",
            "aria-multiselectable",
            "aria-orientation",
            "aria-required",
        ],
        prohibited_attributes: &[],
        deprecated_attributes: &["aria-dropeffect", "aria-grabbed", "aria-haspopup"],
        default_values: &[("aria-orientation", "vertical")],
    },
    Role {
        name: "treegrid",
        is_abstract: false,
        superclasses: &["grid", "tree"],
        ancestors: &[
            "grid",
            "composite",
            "widget",
            "roletype",
            "table",
            "section",
            "structure",
            "tree",
            "select",
            "group",
        ],
        required_context: &[],
        required_owned: &[
            OwnedElement {
                role: "row",
                via: None,
            },
            OwnedElement {
                role: "row",
                via: Some("rowgroup"),
            },
        ],
        name_from: &[NameFrom::Author],
        children_presentational: false,
        specific_attributes: &[
            "aria-activedescendant",
            "aria-colcount",
            "aria-multiselectable",
            "aria-orientation",
            "aria-readonly",
            "aria-required",
            "aria-rowcount",
        ],
        prohibited_attributes: &[],
        deprecated_attributes: &[
            "aria-dropeffect",
            "aria-errormessage",
            "aria-grabbed",
            "aria-haspopup",
            "aria-invalid",
        ],
        default_values: &[("aria-orientation", "vertical")],
    },
    Role {
        name: "treeitem",
        is_abstract: false,
        superclasses: &["listitem", "option"],
        ancestors: &[
            "listitem",
            "section",
            "structure",
            "roletype",
            "option",
            "input",
            "widget",
        ],
        required_context: &["group", "tree"],
        required_owned: &[],
        name_from: &[NameFrom::Author, NameFrom::Contents],
        children_presentational: false,
        specific_attributes: &[
            "aria-checked",
            "aria-expanded",
            "aria-level",
            "aria-posinset",
            "aria-selected",
            "aria-setsize",
        ],
        prohibited_attributes: &[],
        deprecated_attributes: &[
            "aria-disabled",
            "aria-dropeffect",
            "aria-errormessage",
            "aria-grabbed",
            "aria-invalid",
        ],
        default_values: &[("aria-selected", "false")],
    },
    Role {
        name: "widget",
        is_abstract: true,
        superclasses: &["roletype"],
        ancestors: &["roletype"],
        required_context: &[],
        required_owned: &[],
        name_from: &[],
        children_presentational: false,
        specific_attributes: &[],
        prohibited_attributes: &[],
        deprecated_attributes: &[
            "aria-disabled",
            "aria-dropeffect",
            "aria-errormessage",
            "aria-grabbed",
            "aria-haspopup",
            "aria-invalid",
        ],
        default_values: &[],
    },
    Role {
        name: "window",
        is_abstract: true,
        superclasses: &["roletype"],
        ancestors: &["roletype"],
        required_context: &[],
        required_owned: &[],
        name_from: &[NameFrom::Author],
        children_presentational: false,
        specific_attributes: &["aria-modal"],
        prohibited_attributes: &[],
        deprecated_attributes: &[
            "aria-disabled",
            "aria-dropeffect",
            "aria-errormessage",
            "aria-grabbed",
            "aria-haspopup",
            "aria-invalid",
        ],
        default_values: &[],
    },
];
